# Generated by Django 5.2.7 on 2025-12-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=3),
        ),
    ]
